version: '3'
services:
  rails:
    build:
      context: ./rails
    command: bash -c "tail -f log/development.log"
    volumes:
      - ./rails:/myapp
      - /etc/ssl/cert.pem:/etc/ssl/cert.pem
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
  next:
    build:
      dockerfile: ./next/Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ./next:/app
    ports:
      - "8000:3000"
